kind: pipeline
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      semantic_release: false
      git_method: gh
      git_user_name:
        from_secret: github_username
      git_user_email:
        from_secret: github_email
      github_token:
        from_secret: github_token
      update_readme_toc: true
      update_docker_readme: false
      docker_username:
        from_secret: docker_hub_username
      docker_password:
        from_secret: docker_hub_password
      docker_repo: cenk1cenk2/drone-semantic-release

  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/drone-semantic-release
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tag:
        - latest
